"""empty message

Revision ID: 39523b65b5f2
Revises: eae825fb718c
Create Date: 2019-11-03 05:38:19.679171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39523b65b5f2'
down_revision = 'eae825fb718c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
